version: '3'
services:
  devbox:
    build:
      context: ./
      dockerfile: DevBox.DockerFile
    ports:
      - "8080:80"
      - "4430:443"
    volumes:
      - /Users/nirmk/Documents/docker_docked/docker_compose/lamp_stack_dc/php_files:/var/www/html
  devmysql:
    build:
      context: ./
      dockerfile: MySQLDev.DockerFile
    ports:
      - "55555:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    restart: always
    volumes:
            - /Users/nirmk/Documents/docker_docked/docker_compose/lamp_stack_dc/mysql_database:/var/lib/mysql